import type { Category, Place, Review } from '../types'

export const MOCK_PLACES: Record<string, Partial<Record<Category, Place[]>>> = {
  Rome: {
    restaurants: [
      {
        id: 'rome-rest-1',
        rank: 1,
        name: 'Trattoria Da Enzo al 29',
        category: 'restaurants',
        subCategory: 'trattorias',
        rating: 4.8,
        reviewCount: 3240,
        price: '€€',
        cluster: 'Trastevere',
        address: 'Via dei Vascellari 29, Trastevere',
        description: 'Legendary carciofo alla giudia, authentic carbonara, and cacio e pepe in the cobblestone heart of Trastevere.',
        photo: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8885,
        lng: 12.4789,
        openStatus: 'Open · Closes 23:00',
        michelin: true,
        tags: ['Michelin Bib Gourmand', 'Authentic Roman', 'Cacio e Pepe'],
      },
      {
        id: 'rome-rest-2',
        rank: 2,
        name: 'Roscioli Salumeria con Cucina',
        category: 'restaurants',
        subCategory: 'wine_bars',
        rating: 4.7,
        reviewCount: 4810,
        price: '€€€',
        cluster: 'Centro Storico',
        address: "Via dei Giubbonari 21, Campo de' Fiori",
        description: 'Iconic gourmet destination with 2,800 wine labels, legendary crispy guanciale carbonara, and aged burrata.',
        photo: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8942,
        lng: 12.4740,
        openStatus: 'Open · Closes 00:00',
        tags: ['Iconic Carbonara', 'Wine Cellar', 'Gourmet Deli'],
      },
      {
        id: 'rome-rest-3',
        rank: 3,
        name: 'Seu Pizza Illuminati',
        category: 'restaurants',
        subCategory: 'pizzerias',
        rating: 4.7,
        reviewCount: 1950,
        price: '€€',
        cluster: 'Trastevere',
        address: 'Via Angelo Bargoni 10, Portuense',
        description: 'Award-winning contemporary pizza creations with puffy airy crusts and avant-garde Italian seasonal toppings.',
        photo: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8790,
        lng: 12.4715,
        openStatus: 'Open · Closes 23:30',
        tags: ['Top 50 Pizza Italy', 'Modern Crust', 'Craft Beer'],
      },
      {
        id: 'rome-rest-4',
        rank: 4,
        name: 'Osteria da Fortunata',
        category: 'restaurants',
        subCategory: 'trattorias',
        rating: 4.6,
        reviewCount: 5620,
        price: '€€',
        cluster: 'Centro Storico',
        address: 'Via del Pellegrino 11, Parione',
        description: 'Fresh pasta hand-rolled live in front of your table: taglionlini, strozzapreti, and rich oxtail coda alla vaccinara.',
        photo: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8961,
        lng: 12.4718,
        openStatus: 'Open · Closes 01:00',
        tags: ['Handmade Pasta Live', 'Family Tradition', 'Coda alla Vaccinara'],
      },
      {
        id: 'rome-rest-5',
        rank: 5,
        name: 'Pizzeria Da Remo',
        category: 'restaurants',
        subCategory: 'pizzerias',
        rating: 4.6,
        reviewCount: 2890,
        price: '€€',
        cluster: 'Testaccio',
        address: 'Piazza Santa Maria Liberatrice 44, Testaccio',
        description: 'Bustling neighborhood staple serving ultra-thin Roman style wood-fired pizzas with crispy blistered crusts.',
        photo: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8785,
        lng: 12.4772,
        openStatus: 'Open · Closes 23:00',
        tags: ['Classic Roman Thin Crust', 'Suppli', 'Local Favorite'],
      },
      {
        id: 'rome-rest-6',
        rank: 6,
        name: 'Armando al Pantheon',
        category: 'restaurants',
        subCategory: 'fine_dining',
        rating: 4.8,
        reviewCount: 4120,
        price: '€€€',
        cluster: 'Centro Storico',
        address: "Salita de' Crescenzi 31, Centro Storico",
        description: 'Historic fine trattoria beside the Pantheon, serving refined Roman classics like amatriciana and pigeon since 1961.',
        photo: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8988,
        lng: 12.4764,
        openStatus: 'Open · Closes 23:00',
        michelin: true,
        tags: ['Michelin Guide', 'Beside Pantheon', 'Historic Gem'],
      },
      {
        id: 'rome-rest-7',
        rank: 7,
        name: 'Frigidarium Gelateria',
        category: 'restaurants',
        subCategory: 'gelato',
        rating: 4.9,
        reviewCount: 6300,
        price: '€',
        cluster: 'Centro Storico',
        address: 'Via del Governo Vecchio 112, Navona',
        description: 'Legendary artisanal gelato with all-natural ingredients, dipped for free in dark or white chocolate shells.',
        photo: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8979,
        lng: 12.4695,
        openStatus: 'Open · Closes 01:00',
        tags: ['Artisanal Gelato', 'Free Chocolate Dip', 'Pistacchio Bronte'],
      }
    ],
    attractions: [
      {
        id: 'rome-att-1',
        rank: 1,
        name: 'Colosseum & Roman Forum',
        category: 'attractions',
        rating: 4.9,
        reviewCount: 84200,
        price: '€18',
        cluster: 'Monti',
        address: 'Piazza del Colosseo 1, Monti',
        description: 'Iconic ancient amphitheater of gladiatorial combat and the heart of the Roman Empire civilization.',
        photo: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8902,
        lng: 12.4922,
        openStatus: 'Open · Closes 19:15',
        tags: ['UNESCO World Heritage', 'Ancient Rome', 'Skip the Line'],
      },
      {
        id: 'rome-att-2',
        rank: 2,
        name: 'Pantheon',
        category: 'attractions',
        rating: 4.9,
        reviewCount: 62000,
        price: '€5',
        cluster: 'Centro Storico',
        address: 'Piazza della Rotonda, Centro Storico',
        description: '2,000-year-old architectural marvel with the worlds largest unreinforced concrete dome and sunlit oculus.',
        photo: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8986,
        lng: 12.4769,
        openStatus: 'Open · Closes 19:00',
        tags: ['Ancient Temple', 'Raphael Tomb', 'Iconic Dome'],
      },
      {
        id: 'rome-att-3',
        rank: 3,
        name: 'Trevi Fountain',
        category: 'attractions',
        rating: 4.8,
        reviewCount: 91400,
        price: 'Free',
        cluster: 'Centro Storico',
        address: 'Piazza di Trevi, Trevi',
        description: 'Baroque masterpiece fountain featuring Oceanus; toss a coin to guarantee your return to the Eternal City.',
        photo: 'https://images.unsplash.com/photo-1525874684015-58379d421a52?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.9009,
        lng: 12.4833,
        openStatus: 'Open 24/7',
        tags: ['Baroque Fountain', 'Night Illuminations', 'Must Visit'],
      }
    ],
    hotels: [
      {
        id: 'rome-hot-1',
        rank: 1,
        name: 'Hotel Eden - Dorchester Collection',
        category: 'hotels',
        rating: 4.9,
        reviewCount: 2400,
        price: '€€€€',
        cluster: 'Monti',
        address: 'Via Ludovisi 49, Ludovisi',
        description: 'Ultra-luxurious 5-star palace near Villa Borghese with Michelin-starred rooftop dining overlooking St. Peters.',
        photo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.9068,
        lng: 12.4878,
        openStatus: '24/7 Front Desk',
        tags: ['5-Star Luxury', 'Rooftop Spa', 'Michelin Dining'],
      }
    ],
    tours: [
      {
        id: 'rome-tour-1',
        rank: 1,
        name: 'Trastevere Sunset Food & Wine Walking Tour',
        category: 'tours',
        rating: 4.9,
        reviewCount: 3800,
        price: '€75',
        cluster: 'Trastevere',
        address: 'Piazza Trilussa, Trastevere',
        description: 'Taste 12+ authentic Roman specialties paired with fine Lazio wines through secret wine cellars and bakeries.',
        photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8900,
        lng: 12.4705,
        openStatus: 'Daily departures at 17:00',
        tags: ['12 Tastings', 'Wine Included', 'Expert Sommelier Guide'],
      }
    ],
    inspire: [
      {
        id: 'rome-ins-1',
        rank: 1,
        name: 'Gianicolo Hill Sunset Belvedere',
        category: 'inspire',
        rating: 4.8,
        reviewCount: 4200,
        price: 'Free',
        cluster: 'Trastevere',
        address: 'Piazzale Giuseppe Garibaldi, Gianicolo',
        description: 'The highest romantic panoramic viewpoint in Rome overlooking bell towers, domes, and the Apennine mountains.',
        photo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 41.8918,
        lng: 12.4616,
        openStatus: 'Open 24/7',
        tags: ['Panoramic Sunset', 'Romantic Lookout', 'Garibaldi Cannon'],
      }
    ]
  },
  Manila: {
    restaurants: [
      {
        id: 'mnl-rest-1',
        rank: 1,
        name: 'Barbara\'s Heritage Restaurant',
        category: 'restaurants',
        subCategory: 'trattorias',
        rating: 4.6,
        reviewCount: 1840,
        price: '₱₱',
        cluster: 'Intramuros',
        address: 'Plaza San Luis Complex, General Luna St, Intramuros, Manila',
        description: 'Authentic Filipino and Spanish buffet dining accompanied by cultural folk dances in historic Intramuros.',
        photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 14.5888,
        lng: 120.9753,
        openStatus: 'Open · Closes 21:00',
        tags: ['Cultural Dance', 'Buffet', 'Spanish Colonial'],
      }
    ]
  },
  Tokyo: {
    restaurants: [
      {
        id: 'tky-rest-1',
        rank: 1,
        name: 'Sukiyabashi Jiro & Ginza Dining',
        category: 'restaurants',
        subCategory: 'fine_dining',
        rating: 4.9,
        reviewCount: 3100,
        price: '¥¥¥¥',
        cluster: 'Ginza',
        address: 'Tsukamoto Sogyo Bldg., Ginza, Chuo-ku, Tokyo',
        description: 'World-renowned Edo-style sushi craftsmanship prepared with meticulous dedication to perfection.',
        photo: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
        url: 'https://www.tripadvisor.com',
        lat: 35.6719,
        lng: 139.7640,
        openStatus: 'Open by reservation',
        tags: ['3 Michelin Stars', 'Master Chef', 'Edo-Mae Sushi'],
      }
    ]
  }
}

export const MOCK_REVIEWS: Record<string, Review[]> = {
  'rome-rest-1': [
    {
      id: 201,
      title: 'Best cacio e pepe in Rome by far!',
      text: 'The carciofo alla giudia was crispy and savory, and the pasta was cooked to absolute perfection. Arrive before opening!',
      rating: 5,
      user: { username: 'Marco B.', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=80' },
      date: '2 days ago',
    },
    {
      id: 202,
      title: 'Pure magic in Trastevere',
      text: 'Atmospheric outdoor seating on cobblestones, attentive service, and decadent tiramisu with mascarpone cream.',
      rating: 5,
      user: { username: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80' },
      date: '1 week ago',
    },
  ],
  'rome-rest-2': [
    {
      id: 203,
      title: 'Unbelievable carbonara',
      text: 'Rich egg yolk sauce, crunchy smoked guanciale, and pairing recommendations from their incredible wine vault.',
      rating: 5,
      user: { username: 'Alessandro R.' },
      date: '3 days ago',
    },
  ],
}

export function getFallbackPlaces(category: Category, city: string): Place[] {
  const cityData = MOCK_PLACES[city]
  if (cityData && cityData[category] && cityData[category]!.length > 0) {
    return cityData[category]!
  }

  // Fallback generic generator
  const baseLat = city === 'Rome' ? 41.89 :
                  city === 'Tokyo' ? 35.68 :
                  city === 'Singapore' ? 1.35 : 14.59
  const baseLng = city === 'Rome' ? 12.48 :
                  city === 'Tokyo' ? 139.76 :
                  city === 'Singapore' ? 103.81 : 120.98

  const categoryTitles: Record<Category, string[]> = {
    restaurants: [`Trattoria Bella ${city}`, `Osteria Antica ${city}`, `La Bottega Gourmet ${city}`, `Pizzeria Rustica ${city}`],
    hotels: [`${city} Grand Oasis Hotel`, `The Skyline Suites ${city}`, `Boutique Heritage Inn ${city}`],
    attractions: [`Historic Center of ${city}`, `${city} Cultural Arts Pavilion`, `${city} Sky Promenade`],
    tours: [`Essential ${city} Highlights Guided Tour`, `${city} Sunset & Food Discovery Tour`],
    inspire: [`Panoramic Belvedere ${city}`, `${city} Waterfront Promenade`]
  }

  const photos = [
    'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=800&q=80',
  ]

  const titles = categoryTitles[category] || categoryTitles.restaurants

  return titles.map((title, idx) => ({
    id: `mock-${city.toLowerCase()}-${category}-${idx + 1}`,
    rank: idx + 1,
    name: title,
    category,
    rating: Number((4.5 + idx * 0.1).toFixed(1)),
    reviewCount: 1200 + idx * 650,
    price: idx % 2 === 0 ? '€€' : '€€€',
    cluster: idx % 2 === 0 ? 'Centro Storico' : 'Trastevere',
    address: `Via del Corso ${10 + idx * 12}, ${city}`,
    description: `Renowned destination for incredible local flavors, world-class hospitality, and historic charm in ${city}.`,
    photo: photos[idx % photos.length],
    url: 'https://www.tripadvisor.com',
    lat: baseLat + (idx * 0.006 - 0.004),
    lng: baseLng + (idx * 0.007 - 0.003),
    openStatus: 'Open · Closes 23:30',
    tags: ['Handcrafted', 'Top Rated', 'Verified'],
  }))
}
